sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: moveit_octomap_point_cloud
    max_range: 5.0
    point_subsample: 1 # Choose one of every point_subsample points
    padding_offset: 0.0
    padding_scale: 1.0
    max_update_rate: 1.0
    filtered_cloud_topic: octomap_updater_filtered_cloud
